version: "3"

services:
    ubuntussh:
        build: ./ubuntussh
    ansiblelocal:
        build: ./ansible
        environment:
            - MAX_ANSIBLE_NODES=${MAX_ANSIBLE_NODES}
        volumes:
            - ./public_playbooks:/public_playbooks
            - ./private_playbooks:/private_playbooks
        depends_on:
          - ubuntussh

