version: "3"

services:
    ubuntussh:
        build: ./ubuntussh
    ansiblelocal:
        build: ./ansible
        environment:
            - MAX_ANSIBLE_NODES=${MAX_ANSIBLE_NODES}
        depends_on:
          - ubuntussh

